# Generated by Django 2.0.5 on 2018-08-16 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0002_auto_20180816_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
