# Generated by Django 2.0.5 on 2018-08-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0003_auto_20180816_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseApartmentVilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(default=1)),
                ('floors', models.IntegerField(default=1)),
                ('bedroom_master', models.IntegerField(default=1)),
                ('bedroom', models.IntegerField(default=1)),
                ('kitchen', models.IntegerField(default=1)),
                ('bathroom', models.IntegerField(default=1)),
                ('pool', models.IntegerField(default=0)),
                ('laundry', models.IntegerField(default=0)),
                ('gym', models.IntegerField(default=0)),
                ('entertainment', models.IntegerField(default=0)),
                ('carpark', models.IntegerField(default=0)),
                ('accommodation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accomodation.Accomodation')),
            ],
        ),
    ]
